# Generated by Django 4.1.4 on 2022-12-12 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datos',
            new_name='Proyecto',
        ),
    ]
